# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "ZEL Energy Blog"
description: >
  Updates, insights, and stories from ZEL Energy.

email: hello@zelenergy.co

# blog logo (file is literally: assets/images/1.png)
logo: "/assets/images/1.png"
float_logo: true

# blog cover image
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: "ZEL Energy"
author: "ZEL Energy"
author_image: "/assets/images/author.jpg"

paginate: 5

# GitHub Pages â€“ project site
url: "https://baseddbu.github.io"
baseurl: "/zelenergy-blog"

# social icons (Font Awesome 4.2 compatible)
social:
  - icon: linkedin
    url: https://www.linkedin.com/company/zel-energy/
    desc: Follow us on LinkedIn

  - icon: globe
    url: https://zelenergy.co
    desc: Visit zelenergy.co
