# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "ZEL Energy Blog"
description: > # this means to ignore newlines until "email:"
  Updates, insights, and stories from ZEL Energy.

email: hello@zelenergy.co

# blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: "ZEL Energy"
author: "ZEL Energy"
author_image: "/assets/images/author.jpg"

paginate: 5

# IMPORTANT: Project site on GitHub Pages
url: "https://baseddbu.github.io"
baseurl: "/zelenergy-blog"

# used to display twitter cards
twitter_handle: "@zelenergy"

# fill in disqus shortname to use disqus
# disqus: disqus-shortname

# google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/zelenergy
    desc: Follow us on X
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/baseddbu/zelenergy-blog
    desc: Fork this blog on GitHub
    share_url:
    share_title:
    share_link:
